apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-one
  namespace: stage-04-SITE
  labels:
    app: nginx-one
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-one
  template:
    metadata:
      labels:
        app: nginx-one
    spec:
      containers:
        - name: nginx
          image: nginx:1.26.2
          ports:
            - containerPort: 8080
              protocol: TCP  
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            limits:
              memory: "50Mi"
            requests:
              memory: "50Mi"
              cpu: "250m"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 1001
        runAsGroup: 1001
        runAsNonRoot: true
        strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1