apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-depo
  labels:
    app: nginx-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-1
  template:
    metadata:
      labels:
        app: nginx-1
    spec:
      containers:
      - name: venera-site
        image: privatebin/nginx-fpm-alpine:latest
        volumeMounts:
        - name: website-content
          mountPath: /var/lib/nginx/html
        ports:
        - containerPort: 80
      volumes:
      - name: website-content
        persistentVolumeClaim:
          claimName: website-pvc
